#!/usr/bin/env python3
"""Generate the small ROM story demo used for hardware acceptance."""

from __future__ import annotations

import argparse
import struct
import wave
from pathlib import Path


FRAME_LEN = 5000
HEADER_LEN = 16
RECORD_LEN = 5004
SAMPLE_RATE = 16000
DEMO_AUDIO_BLOCK_SAMPLES = 256

IMA_INDEX_TABLE = (-1, -1, -1, -1, 2, 4, 6, 8)
IMA_STEP_TABLE = (
    7, 8, 9, 10, 11, 12, 13, 14, 16, 17, 19, 21, 23, 25, 28, 31,
    34, 37, 41, 45, 50, 55, 60, 66, 73, 80, 88, 97, 107, 118, 130,
    143, 157, 173, 190, 209, 230, 253, 279, 307, 337, 371, 408, 449,
    494, 544, 598, 658, 724, 796, 876, 963, 1060, 1166, 1282, 1411,
    1552, 1707, 1878, 2066, 2272, 2499, 2749, 3024, 3327, 3660, 4026,
    4428, 4871, 5358, 5894, 6484, 7132, 7845, 8630, 9493, 10442, 11487,
    12635, 13899, 15289, 16818, 18500, 20350, 22385, 24623, 27086, 29794,
    32767,
)


def c_bytes(name: str, values: bytes) -> str:
    lines = [f"const uint8_t {name}[{len(values)}] = {{"]
    for index in range(0, len(values), 16):
        lines.append("    " + ", ".join(f"0x{value:02X}" for value in values[index:index + 16]) + ",")
    lines.append("};")
    return "\n".join(lines)


def c_samples(name: str, values: tuple[int, ...]) -> str:
    lines = [f"const int16_t {name}[{len(values)}] = {{"]
    for index in range(0, len(values), 16):
        lines.append("    " + ", ".join(str(value) for value in values[index:index + 16]) + ",")
    lines.append("};")
    return "\n".join(lines)


def read_demo_audio(wav_path: Path) -> tuple[int, ...]:
    with wave.open(str(wav_path), "rb") as audio:
        if (audio.getframerate(), audio.getnchannels(), audio.getsampwidth()) != (SAMPLE_RATE, 1, 2):
            raise ValueError(f"demo WAV must be mono 16kHz 16-bit PCM: {wav_path}")
        raw = audio.readframes(audio.getnframes())
    return struct.unpack("<" + "h" * (len(raw) // 2), raw)


def clip16(value: int) -> int:
    return max(-32768, min(32767, value))


def ima_encode(samples: tuple[int, ...]) -> bytes:
    """Encode mono PCM as independent 256-sample IMA ADPCM blocks."""
    if not samples:
        raise ValueError("audio scene is empty")

    encoded = bytearray()
    for start in range(0, len(samples), DEMO_AUDIO_BLOCK_SAMPLES):
        block = samples[start:start + DEMO_AUDIO_BLOCK_SAMPLES]
        predictor = int(block[0])
        index = 0
        encoded.extend(struct.pack("<hBB", predictor, index, 0))
        pending = None

        for sample in block[1:]:
            step = IMA_STEP_TABLE[index]
            difference = int(sample) - predictor
            code = 0
            if difference < 0:
                code = 8
                difference = -difference

            residual = difference
            if residual >= step:
                code |= 4
                residual -= step
            if residual >= (step >> 1):
                code |= 2
                residual -= step >> 1
            if residual >= (step >> 2):
                code |= 1

            delta = step >> 3
            if code & 4:
                delta += step
            if code & 2:
                delta += step >> 1
            if code & 1:
                delta += step >> 2
            predictor = clip16(predictor - delta if code & 8 else predictor + delta)
            index = max(0, min(88, index + IMA_INDEX_TABLE[code & 7]))

            if pending is None:
                pending = code
            else:
                encoded.append(pending | (code << 4))
                pending = None

        if pending is not None:
            encoded.append(pending)

    return bytes(encoded)


def build(fvid: Path, audio_dir: Path, out_dir: Path) -> None:
    data = fvid.read_bytes()
    if data[:4] != b"FVID" or len(data) < HEADER_LEN:
        raise ValueError(f"invalid FVID: {fvid}")
    width, height, count = struct.unpack_from("<HHH", data, 6)
    if (width, height) != (200, 200):
        raise ValueError("story demo requires 200x200 frames")
    if len(data) != HEADER_LEN + count * RECORD_LEN:
        raise ValueError("FVID length does not match its header")

    frames = []
    hints = []
    for index in range(count):
        offset = HEADER_LEN + index * RECORD_LEN
        hints.append(data[offset])
        frames.append(data[offset + 4:offset + RECORD_LEN])

    audio_scenes = []
    encoded_audio_scenes = []
    for index in range(count):
        wav_path = audio_dir / f"{index:03d}.wav"
        if not wav_path.is_file():
            raise FileNotFoundError(f"missing scene audio: {wav_path}")
        samples = read_demo_audio(wav_path)
        audio_scenes.append(samples)
        encoded_audio_scenes.append(ima_encode(samples))

    out_dir.mkdir(parents=True, exist_ok=True)
    header = """/* Generated by tools/build_story_demo_assets.py. Do not edit by hand. */
#pragma once

#include <stdint.h>

#define STORY_DEMO_FRAME_LEN 5000
extern const uint8_t* const STORY_DEMO_FRAMES[];
extern const uint8_t STORY_DEMO_REFRESH_HINTS[];
extern const int STORY_DEMO_FRAME_COUNT;
"""
    parts = ["/* Generated by tools/build_story_demo_assets.py. Do not edit by hand. */", '#include "story_demo_assets.h"', ""]
    for index, frame in enumerate(frames):
        parts.extend([c_bytes(f"STORY_DEMO_FRAME_{index:02d}", frame), ""])
    parts.append("const uint8_t* const STORY_DEMO_FRAMES[] = {")
    parts.extend(f"    STORY_DEMO_FRAME_{index:02d}," for index in range(count))
    parts.extend(["};", "", "const uint8_t STORY_DEMO_REFRESH_HINTS[] = {"])
    parts.append("    " + ", ".join(str(value) for value in hints) + ",")
    parts.extend(["};", f"const int STORY_DEMO_FRAME_COUNT = {count};", ""])
    (out_dir / "story_demo_assets.h").write_text(header, encoding="utf-8")
    (out_dir / "story_demo_assets.c").write_text("\n".join(parts), encoding="utf-8")

    audio_header = """/* Generated by tools/build_story_demo_assets.py. Do not edit by hand. */
#pragma once

#include <stdint.h>

#define STORY_DEMO_AUDIO_SAMPLE_RATE 16000
#define STORY_DEMO_AUDIO_SCENE_COUNT %d
extern const uint8_t* const STORY_DEMO_AUDIO_DATA[];
extern const uint32_t STORY_DEMO_AUDIO_DATA_LENGTHS[];
extern const uint32_t STORY_DEMO_AUDIO_SAMPLE_COUNTS[];
""" % len(audio_scenes)
    audio_source = "\n".join([
        "/* Generated by tools/build_story_demo_assets.py. Do not edit by hand. */",
        '#include "story_demo_audio.h"',
        "",
    ] + sum(([c_bytes(f"STORY_DEMO_AUDIO_DATA_{index:02d}", data), ""]
             for index, data in enumerate(encoded_audio_scenes)), []) + [
        "const uint8_t* const STORY_DEMO_AUDIO_DATA[] = {",
        *[f"    STORY_DEMO_AUDIO_DATA_{index:02d}," for index in range(len(audio_scenes))],
        "};",
        "",
        "const uint32_t STORY_DEMO_AUDIO_DATA_LENGTHS[] = {",
        "    " + ", ".join(str(len(data)) for data in encoded_audio_scenes) + ",",
        "};",
        "",
        "const uint32_t STORY_DEMO_AUDIO_SAMPLE_COUNTS[] = {",
        "    " + ", ".join(str(len(samples)) for samples in audio_scenes) + ",",
        "};",
        "",
    ])
    (out_dir / "story_demo_audio.h").write_text(audio_header, encoding="utf-8")
    (out_dir / "story_demo_audio.c").write_text(audio_source, encoding="utf-8")
    print(f"frames: {count} -> {out_dir / 'story_demo_assets.c'}")
    total_samples = sum(len(samples) for samples in audio_scenes)
    total_encoded = sum(len(data) for data in encoded_audio_scenes)
    print(f"audio: {len(audio_scenes)} scenes, {total_samples} samples "
          f"({total_samples / SAMPLE_RATE:.2f}s), {total_encoded} ADPCM bytes "
          f"-> {out_dir / 'story_demo_audio.c'}")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--fvid", default="assets/stories/fox_forest/fox_forest.fvid")
    parser.add_argument("--audio-dir", default="assets/stories/fox_forest/fox_forest/audio")
    parser.add_argument("--out-dir", default="assets/generated")
    args = parser.parse_args()
    build(Path(args.fvid), Path(args.audio_dir), Path(args.out_dir))


if __name__ == "__main__":
    main()
