#!/usr/bin/env python3
"""
Build the single-character prelude plus staged group e-paper asset pack.

The generated C interface intentionally matches tools/video2c.py so firmware can
keep using APP_VIDEO_FRAMES unchanged.
"""

import argparse
from pathlib import Path

import numpy as np
from PIL import Image, ImageOps

from _fvid import emit_fvid, refresh_hints

ROOT = Path(__file__).resolve().parent.parent
SRC_DIR = ROOT / "assets" / "src"
OUT_DIR = ROOT / "assets" / "generated"
STORY_DIR = OUT_DIR / "story_frames"
GROUP_DIR = OUT_DIR / "video_frames"

CHARACTER_FILES = [
    "Armored_man_standing_heroically_202608091529.jpeg",
    "Blue-haired_mage_holding_staff_202608091529.jpeg",
    "boy_on_green_background_202608091528.jpeg",
    "Character_standing_on_green_screen_202608091529.jpeg",
    "Maid_with_glasses_standing_202608091529.jpeg",
    "Seated_woman_sitting_on_green_202608091529.jpeg",
]


def green_screen_mask(img):
    arr = np.asarray(img.convert("RGB")).astype(np.int16)
    r, g, b = arr[:, :, 0], arr[:, :, 1], arr[:, :, 2]
    green = (g > 105) & (g > r + 28) & (g > b + 22)
    return ~green


def crop_to_mask(img, mask, margin):
    ys, xs = np.where(mask)
    if len(xs) == 0 or len(ys) == 0:
        return img, mask
    x0 = max(0, int(xs.min()) - margin)
    y0 = max(0, int(ys.min()) - margin)
    x1 = min(img.width, int(xs.max()) + margin + 1)
    y1 = min(img.height, int(ys.max()) + margin + 1)
    return img.crop((x0, y0, x1, y1)), mask[y0:y1, x0:x1]


def make_solo_frame(path, size, max_w, max_h, bottom_margin):
    img = Image.open(path).convert("RGB")
    mask = green_screen_mask(img)
    img, mask = crop_to_mask(img, mask, margin=18)

    scale = min(max_w / img.width, max_h / img.height)
    new_size = (max(1, round(img.width * scale)), max(1, round(img.height * scale)))
    img = img.resize(new_size, Image.Resampling.LANCZOS)
    mask_img = Image.fromarray((mask * 255).astype(np.uint8)).resize(
        new_size, Image.Resampling.LANCZOS
    )

    frame = Image.new("RGB", (size, size), "white")
    x = (size - new_size[0]) // 2
    y = size - bottom_margin - new_size[1]
    frame.paste(img, (x, y), mask_img)
    return frame


def threshold_image(img, threshold):
    gray = ImageOps.grayscale(img)
    arr = np.asarray(gray).astype(np.float32)
    return arr < threshold


def despeckle(ink, min_neighbors):
    if min_neighbors <= 0:
        return ink
    p = np.pad(ink.astype(np.uint8), 1)
    acc = np.zeros(ink.shape, dtype=np.uint8)
    for dy in range(3):
        for dx in range(3):
            if dy == 1 and dx == 1:
                continue
            acc += p[dy : dy + ink.shape[0], dx : dx + ink.shape[1]]
    return ink & (acc >= min_neighbors)


def pack_native(ink):
    h, w = ink.shape
    stride = (w + 7) // 8
    out = np.full((h, stride), 0xFF, dtype=np.uint8)
    for x in range(w):
        out[:, x >> 3] &= np.where(
            ink[:, x],
            np.uint8(~(0x80 >> (x & 7)) & 0xFF),
            np.uint8(0xFF),
        )
    return out.reshape(-1)


def c_array(name, data):
    lines = [f"const uint8_t {name}[{len(data)}] = {{"]
    for i in range(0, len(data), 16):
        chunk = ", ".join(f"0x{b:02X}" for b in data[i : i + 16])
        lines.append(f"    {chunk},")
    lines.append("};")
    return "\n".join(lines)


def emit_assets(frames, width, height, out_dir):
    header = f"""/* Generated by tools/solo_story2c.py. Do not edit by hand. */
#pragma once

#include <stdint.h>

#define APP_VIDEO_FRAME_W {width}
#define APP_VIDEO_FRAME_H {height}
#define APP_VIDEO_FRAME_LEN {width * height // 8}

extern const uint8_t* const APP_VIDEO_FRAMES[];
extern const int APP_VIDEO_FRAME_COUNT;
"""
    (out_dir / "family_video_assets.h").write_text(header, encoding="utf-8")

    parts = [
        "/* Generated by tools/solo_story2c.py. Do not edit by hand. */",
        '#include "family_video_assets.h"',
        "",
    ]
    for idx, data in enumerate(frames):
        parts.append(c_array(f"APP_VIDEO_FRAME_{idx:02d}", data))
        parts.append("")

    parts.append("const uint8_t* const APP_VIDEO_FRAMES[] = {")
    for idx in range(len(frames)):
        parts.append(f"    APP_VIDEO_FRAME_{idx:02d},")
    parts.append("};")
    parts.append(f"const int APP_VIDEO_FRAME_COUNT = {len(frames)};")
    parts.append("")
    (out_dir / "family_video_assets.c").write_text("\n".join(parts), encoding="utf-8")


def emit_preview(inks, out_dir, scale):
    thumbs = []
    for ink in inks:
        img = Image.fromarray(np.where(ink, 0, 255).astype(np.uint8))
        thumbs.append(
            img.resize(
                (ink.shape[1] * scale, ink.shape[0] * scale),
                Image.Resampling.NEAREST,
            )
        )
    strip = Image.new("L", (thumbs[0].width * len(thumbs), thumbs[0].height), 255)
    for idx, img in enumerate(thumbs):
        strip.paste(img, (idx * img.width, 0))
    strip.save(out_dir / "video_preview.png")
    thumbs[-1].save(out_dir / "video_preview_final.png")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--size", type=int, default=200)
    ap.add_argument("--threshold", type=int, default=190)
    ap.add_argument("--despeckle", type=int, default=1)
    ap.add_argument("--solo-threshold", type=int, default=226)
    ap.add_argument("--solo-despeckle", type=int, default=0)
    ap.add_argument("--scale", type=int, default=3)
    ap.add_argument("--max-w", type=int, default=165)
    ap.add_argument("--max-h", type=int, default=188)
    ap.add_argument("--bottom-margin", type=int, default=4)
    ap.add_argument("--format", choices=["c", "fvid"], default="c")
    ap.add_argument("--fvid-out", default=str(OUT_DIR / "solo.fvid"))
    args = ap.parse_args()

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    STORY_DIR.mkdir(parents=True, exist_ok=True)

    solo_frames = []
    for idx, name in enumerate(CHARACTER_FILES):
        frame = make_solo_frame(
            SRC_DIR / name,
            args.size,
            args.max_w,
            args.max_h,
            args.bottom_margin,
        )
        out = STORY_DIR / f"solo_stage_{idx:02d}.png"
        frame.save(out)
        solo_frames.append(out)

    if args.format == "fvid":
        rendered = solo_frames
    else:
        group_frames = sorted(GROUP_DIR.glob("video_stage_[0-9][0-9].png"))
        if not group_frames:
            raise FileNotFoundError(f"no staged group frames in {GROUP_DIR}")
        rendered = solo_frames + group_frames

    frames = []
    inks = []
    solo_count = len(CHARACTER_FILES)
    for idx, path in enumerate(rendered):
        img = Image.open(path).convert("RGB").resize((args.size, args.size))
        threshold = args.solo_threshold if idx < solo_count else args.threshold
        min_neighbors = args.solo_despeckle if idx < solo_count else args.despeckle
        ink = despeckle(threshold_image(img, threshold), min_neighbors)
        frames.append(pack_native(ink))
        inks.append(ink)
        print(f"{idx:02d} {path.name} ink {100 * ink.mean():.1f}%")

    if args.format == "c":
        emit_assets(frames, args.size, args.size, OUT_DIR)
    else:
        path = emit_fvid(frames, refresh_hints(inks), args.size, args.size, Path(args.fvid_out))
        print(f"fvid: {path}")
    emit_preview(inks, OUT_DIR, args.scale)
    print(f"\nwrote {len(frames)} frames -> {OUT_DIR}")
    print(f"solo frames: {STORY_DIR}")
    print(f"preview: {OUT_DIR / 'video_preview.png'}")


if __name__ == "__main__":
    main()
