#!/usr/bin/env python3
"""Compose staged full-frame e-paper assets from assets/story_layout.json."""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import numpy as np
from PIL import Image, ImageOps

ROOT = Path(__file__).resolve().parent.parent
LAYOUT = ROOT / "assets" / "story_layout.json"
OUT_DIR = ROOT / "assets" / "generated"
FRAME_DIR = OUT_DIR / "story_composed"


def resolve_path(src: str) -> Path:
    src = src.replace("\\", "/")
    candidates = []
    if src.startswith("../"):
        candidates.append((ROOT / "tools" / src).resolve())
    candidates.append((ROOT / src).resolve())
    candidates.append((LAYOUT.parent / src).resolve())
    for path in candidates:
        if path.exists():
            return path
    raise FileNotFoundError(src)


def fit_background(path: Path, size: tuple[int, int]) -> Image.Image:
    img = Image.open(path).convert("RGB")
    w, h = img.size
    side = min(w, h)
    left = (w - side) // 2
    top = (h - side) // 2
    img = img.crop((left, top, left + side, top + side))
    return img.resize(size, Image.Resampling.BOX)


def paste_person(canvas: Image.Image, person: dict) -> None:
    img = Image.open(resolve_path(person["src"])).convert("RGBA")
    w = int(round(person["w"]))
    h = int(round(person["h"]))
    img = img.resize((w, h), Image.Resampling.LANCZOS)
    canvas.alpha_composite(img, (int(round(person["x"])), int(round(person["y"]))))


def compose_frames(layout: dict) -> list[tuple[int, Image.Image]]:
    screen = layout.get("screen", {"w": 200, "h": 200})
    size = (int(screen["w"]), int(screen["h"]))
    bg = fit_background(resolve_path(layout["background"]["src"]), size).convert("RGBA")

    people = sorted(
        layout.get("people", []),
        key=lambda p: (int(p.get("draw_order", p.get("order", 0))), p.get("name", "")),
    )
    stages = sorted({int(p.get("appear_order", p.get("order", 0))) for p in people})

    frames: list[tuple[int, Image.Image]] = [(0, bg.copy())]
    for stage in stages:
        canvas = bg.copy()
        for person in people:
            appear_order = int(person.get("appear_order", person.get("order", 0)))
            if appear_order <= stage:
                paste_person(canvas, person)
        frames.append((stage, canvas.convert("RGB")))
    return frames


def to_ink(img: Image.Image, threshold: int, contrast: float, despeckle_n: int) -> np.ndarray:
    gray = np.asarray(ImageOps.grayscale(img)).astype(np.float32)
    if contrast != 1.0:
        gray = np.clip((gray - 128.0) * contrast + 128.0, 0, 255)
    ink = gray < threshold
    if despeckle_n:
        ink = despeckle(ink, despeckle_n)
    return ink


def despeckle(ink: np.ndarray, min_neighbors: int) -> np.ndarray:
    p = np.pad(ink.astype(np.uint8), 1)
    acc = np.zeros(ink.shape, dtype=np.uint8)
    for dy in range(3):
        for dx in range(3):
            if dy == 1 and dx == 1:
                continue
            acc += p[dy:dy + ink.shape[0], dx:dx + ink.shape[1]]
    return ink & (acc >= min_neighbors)


def pack_native(ink: np.ndarray) -> np.ndarray:
    """Pack to panel-native bytes: bit 1 = white, bit 0 = black."""
    h, w = ink.shape
    stride = (w + 7) // 8
    out = np.full((h, stride), 0xFF, dtype=np.uint8)
    for x in range(w):
        bit = np.uint8(0x80 >> (x & 7))
        out[:, x >> 3] &= np.where(ink[:, x], np.uint8(~bit & 0xFF), np.uint8(0xFF))
    return out.reshape(-1)


def c_array(name: str, data: np.ndarray) -> str:
    lines = [f"const uint8_t {name}[{len(data)}] = {{"]
    for i in range(0, len(data), 16):
        chunk = ", ".join(f"0x{int(b):02X}" for b in data[i:i + 16])
        lines.append(f"    {chunk},")
    lines.append("};")
    return "\n".join(lines)


def emit_assets(frames: list[np.ndarray], width: int, height: int, out_dir: Path) -> None:
    header = f"""/* Generated by tools/story_layout2c.py. Do not edit by hand. */
#pragma once

#include <stdint.h>

#define APP_VIDEO_FRAME_W {width}
#define APP_VIDEO_FRAME_H {height}
#define APP_VIDEO_FRAME_LEN {width * height // 8}

extern const uint8_t* const APP_VIDEO_FRAMES[];
extern const int APP_VIDEO_FRAME_COUNT;
"""
    (out_dir / "family_video_assets.h").write_text(header, encoding="utf-8")

    parts = [
        "/* Generated by tools/story_layout2c.py. Do not edit by hand. */",
        '#include "family_video_assets.h"',
        "",
    ]
    for idx, data in enumerate(frames):
        parts.append(c_array(f"APP_VIDEO_FRAME_{idx:02d}", data))
        parts.append("")
    parts.append("const uint8_t* const APP_VIDEO_FRAMES[] = {")
    for idx in range(len(frames)):
        parts.append(f"    APP_VIDEO_FRAME_{idx:02d},")
    parts.append("};")
    parts.append(f"const int APP_VIDEO_FRAME_COUNT = {len(frames)};")
    parts.append("")
    (out_dir / "family_video_assets.c").write_text("\n".join(parts), encoding="utf-8")


def emit_previews(stage_frames: list[tuple[int, Image.Image]], inks: list[np.ndarray], frame_dir: Path, scale: int) -> None:
    frame_dir.mkdir(parents=True, exist_ok=True)
    thumbs = []
    for idx, ((stage, rgb), ink) in enumerate(zip(stage_frames, inks)):
        rgb.save(frame_dir / f"story_stage_{idx:02d}_appear_{stage:02d}_rgb.png")
        bw = Image.fromarray(np.where(ink, 0, 255).astype(np.uint8), "L")
        bw.save(frame_dir / f"story_stage_{idx:02d}_appear_{stage:02d}_1x.png")
        thumbs.append(bw.resize((bw.width * scale, bw.height * scale), Image.Resampling.NEAREST))

    strip = Image.new("L", (thumbs[0].width * len(thumbs), thumbs[0].height), 255)
    for idx, thumb in enumerate(thumbs):
        strip.paste(thumb, (idx * thumb.width, 0))
    strip.save(OUT_DIR / "story_preview.png")
    thumbs[-1].save(OUT_DIR / "story_preview_final.png")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--layout", default=str(LAYOUT))
    parser.add_argument("--threshold", type=int, default=190)
    parser.add_argument("--contrast", type=float, default=1.0)
    parser.add_argument("--despeckle", type=int, default=1)
    parser.add_argument("--scale", type=int, default=3)
    args = parser.parse_args()

    layout = json.loads(Path(args.layout).read_text(encoding="utf-8"))
    screen = layout.get("screen", {"w": 200, "h": 200})
    width = int(screen["w"])
    height = int(screen["h"])

    stage_frames = compose_frames(layout)
    inks = [to_ink(img, args.threshold, args.contrast, args.despeckle) for _, img in stage_frames]
    packed = [pack_native(ink) for ink in inks]

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    emit_assets(packed, width, height, OUT_DIR)
    emit_previews(stage_frames, inks, FRAME_DIR, args.scale)

    for (stage, _), ink in zip(stage_frames, inks):
        print(f"stage {stage:2d} ink {100 * ink.mean():5.1f}%")
    print(f"\nwrote {len(packed)} frames -> {OUT_DIR / 'family_video_assets.c'}")
    print(f"preview -> {OUT_DIR / 'story_preview.png'}")


if __name__ == "__main__":
    main()
