#!/usr/bin/env python3
"""
Extract staged full-frame e-paper assets from a video.

Example:
    python tools/video2c.py "C:/path/demo.mp4" 00:01:08 00:02:14

Timecodes use mm:ss:ff by default, where ff is a frame number at the input
video frame rate. This matches short AI videos exported with frame counters.
"""

import argparse
import subprocess
import sys
from fractions import Fraction
from pathlib import Path

import numpy as np
from PIL import Image, ImageOps

ROOT = Path(__file__).resolve().parent.parent
OUT_DIR = ROOT / "assets" / "generated"
FRAME_DIR = OUT_DIR / "video_frames"


def run(cmd):
    return subprocess.run(cmd, check=True, capture_output=True, text=True)


def video_fps(path):
    out = run([
        "ffprobe", "-v", "error",
        "-select_streams", "v:0",
        "-show_entries", "stream=avg_frame_rate",
        "-of", "default=noprint_wrappers=1:nokey=1",
        str(path),
    ]).stdout.strip()
    return float(Fraction(out))


def parse_timecode(tc, fps):
    parts = tc.split(":")
    if len(parts) != 3:
        raise ValueError(f"{tc}: expected mm:ss:ff")
    mm, ss, ff = (int(p) for p in parts)
    return mm * 60.0 + ss + ff / fps


def extract_frame(video, seconds, out_png):
    run([
        "ffmpeg", "-y",
        "-ss", f"{seconds:.6f}",
        "-i", str(video),
        "-frames:v", "1",
        "-q:v", "2",
        str(out_png),
    ])


def fit_square(img, size):
    w, h = img.size
    side = min(w, h)
    left = (w - side) // 2
    top = (h - side) // 2
    img = img.crop((left, top, left + side, top + side))
    return img.resize((size, size), Image.Resampling.BOX)


def threshold_image(img, threshold, invert):
    gray = ImageOps.grayscale(img)
    arr = np.asarray(gray).astype(np.float32)
    ink = arr < threshold
    if invert:
        ink = ~ink
    return ink


def despeckle(ink, min_neighbors):
    if min_neighbors <= 0:
        return ink
    p = np.pad(ink.astype(np.uint8), 1)
    acc = np.zeros(ink.shape, dtype=np.uint8)
    for dy in range(3):
        for dx in range(3):
            if dy == 1 and dx == 1:
                continue
            acc += p[dy:dy + ink.shape[0], dx:dx + ink.shape[1]]
    return ink & (acc >= min_neighbors)


def pack_native(ink):
    """Pack to panel-native bytes: bit 1 = white, bit 0 = black."""
    h, w = ink.shape
    stride = (w + 7) // 8
    out = np.full((h, stride), 0xFF, dtype=np.uint8)
    for x in range(w):
        out[:, x >> 3] &= np.where(
            ink[:, x],
            np.uint8(~(0x80 >> (x & 7)) & 0xFF),
            np.uint8(0xFF),
        )
    return out.reshape(-1)


def c_array(name, data):
    lines = [f"const uint8_t {name}[{len(data)}] = {{"]
    for i in range(0, len(data), 16):
        chunk = ", ".join(f"0x{b:02X}" for b in data[i:i + 16])
        lines.append(f"    {chunk},")
    lines.append("};")
    return "\n".join(lines)


def emit_assets(frames, width, height, out_dir):
    out_dir.mkdir(parents=True, exist_ok=True)
    header = f"""/* Generated by tools/video2c.py. Do not edit by hand. */
#pragma once

#include <stdint.h>

#define APP_VIDEO_FRAME_W {width}
#define APP_VIDEO_FRAME_H {height}
#define APP_VIDEO_FRAME_LEN {width * height // 8}

extern const uint8_t* const APP_VIDEO_FRAMES[];
extern const int APP_VIDEO_FRAME_COUNT;
"""
    (out_dir / "family_video_assets.h").write_text(header, encoding="utf-8")

    parts = ['/* Generated by tools/video2c.py. Do not edit by hand. */',
             '#include "family_video_assets.h"', ""]
    for idx, data in enumerate(frames):
        parts.append(c_array(f"APP_VIDEO_FRAME_{idx:02d}", data))
        parts.append("")

    parts.append("const uint8_t* const APP_VIDEO_FRAMES[] = {")
    for idx in range(len(frames)):
        parts.append(f"    APP_VIDEO_FRAME_{idx:02d},")
    parts.append("};")
    parts.append(f"const int APP_VIDEO_FRAME_COUNT = {len(frames)};")
    parts.append("")
    (out_dir / "family_video_assets.c").write_text("\n".join(parts), encoding="utf-8")


def emit_preview(inks, out_dir, scale):
    if not inks:
        return
    thumbs = []
    for ink in inks:
        img = Image.fromarray(np.where(ink, 0, 255).astype(np.uint8), "L")
        thumbs.append(img.resize((ink.shape[1] * scale, ink.shape[0] * scale),
                                 Image.Resampling.NEAREST))
    strip = Image.new("L", (thumbs[0].width * len(thumbs), thumbs[0].height), 255)
    for idx, img in enumerate(thumbs):
        strip.paste(img, (idx * img.width, 0))
    strip.save(out_dir / "video_preview.png")
    thumbs[-1].save(out_dir / "video_preview_final.png")


def main():
    for stream in (sys.stdout, sys.stderr):
        if hasattr(stream, "reconfigure"):
            stream.reconfigure(encoding="utf-8", errors="replace")

    ap = argparse.ArgumentParser()
    ap.add_argument("video")
    ap.add_argument("timecodes", nargs="+", help="mm:ss:ff timecodes")
    ap.add_argument("--size", type=int, default=200)
    ap.add_argument("--threshold", type=int, default=190)
    ap.add_argument("--despeckle", type=int, default=1)
    ap.add_argument("--invert", action="store_true")
    ap.add_argument("--out", default=str(OUT_DIR))
    ap.add_argument("--frame-dir", default=str(FRAME_DIR))
    ap.add_argument("--scale", type=int, default=3)
    args = ap.parse_args()

    video = Path(args.video)
    if not video.exists():
        raise FileNotFoundError(video)

    out_dir = Path(args.out)
    frame_dir = Path(args.frame_dir)
    frame_dir.mkdir(parents=True, exist_ok=True)

    fps = video_fps(video)
    frames = []
    inks = []
    for idx, tc in enumerate(args.timecodes):
        seconds = parse_timecode(tc, fps)
        raw = frame_dir / f"video_stage_{idx:02d}_raw.png"
        extract_frame(video, seconds, raw)
        img = fit_square(Image.open(raw).convert("RGB"), args.size)
        fitted = frame_dir / f"video_stage_{idx:02d}.png"
        img.save(fitted)
        ink = despeckle(threshold_image(img, args.threshold, args.invert), args.despeckle)
        frames.append(pack_native(ink))
        inks.append(ink)
        print(f"{idx:02d} {tc} -> {seconds:.3f}s ink {100 * ink.mean():.1f}% {fitted}")

    emit_assets(frames, args.size, args.size, out_dir)
    emit_preview(inks, out_dir, args.scale)
    print(f"\nwrote {len(frames)} frames -> {out_dir}")
    print(f"preview: {out_dir / 'video_preview.png'}")


if __name__ == "__main__":
    main()
