#!/usr/bin/env python3
"""
Extract full-frame 1bpp e-paper assets from a video.

Legacy CLI:
    python tools/video2c.py family.mp4 00:00:00 00:01:08

Config-driven CLI:
    python tools/video2c.py --config assets/family_video_config.json
"""

import argparse
import json
import struct
import subprocess
import sys
from datetime import datetime, timezone
from fractions import Fraction
from pathlib import Path

import numpy as np
from PIL import Image, ImageDraw, ImageOps

ROOT = Path(__file__).resolve().parent.parent
OUT_DIR = ROOT / "assets" / "generated"
FRAME_DIR = OUT_DIR / "video_frames"

HINT_PARTIAL = "APP_REFRESH_PARTIAL"
HINT_FULL = "APP_REFRESH_FULL"
HINT_FINAL_FULL = "APP_REFRESH_FINAL_FULL"


def run(cmd):
    return subprocess.run(cmd, check=True, capture_output=True, text=True)


def video_fps(path):
    out = run([
        "ffprobe", "-v", "error",
        "-select_streams", "v:0",
        "-show_entries", "stream=avg_frame_rate",
        "-of", "default=noprint_wrappers=1:nokey=1",
        str(path),
    ]).stdout.strip()
    return float(Fraction(out))


def parse_timecode(tc, fps):
    parts = tc.split(":")
    if len(parts) != 3:
        raise ValueError(f"{tc}: expected mm:ss:ff")
    mm, ss, ff = (int(p) for p in parts)
    return mm * 60.0 + ss + ff / fps


def extract_frame(video, seconds, out_png):
    run([
        "ffmpeg", "-y",
        "-ss", f"{seconds:.6f}",
        "-i", str(video),
        "-frames:v", "1",
        "-q:v", "2",
        str(out_png),
    ])


def fit_square(img, size, crop):
    w, h = img.size
    if crop.get("mode", "square") != "square":
        raise ValueError("only crop.mode='square' is supported")

    scale = float(crop.get("scale", 1.0))
    if scale <= 0:
        raise ValueError("crop.scale must be > 0")

    side = int(min(w, h) / scale)
    side = max(1, min(side, w, h))
    center_x = w / 2 + int(crop.get("offset_x", 0))
    center_y = h / 2 + int(crop.get("offset_y", 0))
    left = int(round(center_x - side / 2))
    top = int(round(center_y - side / 2))
    left = max(0, min(left, w - side))
    top = max(0, min(top, h - side))
    img = img.crop((left, top, left + side, top + side))
    return img.resize((size, size), Image.Resampling.BOX), {
        "source_box": [left, top, left + side, top + side],
        "mode": "square",
        "offset_x": int(crop.get("offset_x", 0)),
        "offset_y": int(crop.get("offset_y", 0)),
        "scale": scale,
    }


def threshold_image(img, threshold, invert):
    gray = ImageOps.grayscale(img)
    arr = np.asarray(gray).astype(np.float32)
    ink = arr < threshold
    if invert:
        ink = ~ink
    return ink


def despeckle(ink, min_neighbors):
    if min_neighbors <= 0:
        return ink
    p = np.pad(ink.astype(np.uint8), 1)
    acc = np.zeros(ink.shape, dtype=np.uint8)
    for dy in range(3):
        for dx in range(3):
            if dy == 1 and dx == 1:
                continue
            acc += p[dy:dy + ink.shape[0], dx:dx + ink.shape[1]]
    return ink & (acc >= min_neighbors)


def pack_native(ink):
    """Pack to panel-native bytes: bit 1 = white, bit 0 = black."""
    h, w = ink.shape
    stride = (w + 7) // 8
    out = np.full((h, stride), 0xFF, dtype=np.uint8)
    for x in range(w):
        out[:, x >> 3] &= np.where(
            ink[:, x],
            np.uint8(~(0x80 >> (x & 7)) & 0xFF),
            np.uint8(0xFF),
        )
    return out.reshape(-1)


def change_pct(prev, cur):
    if prev is None:
        return 100.0
    return 100.0 * np.count_nonzero(prev != cur) / cur.size


def refresh_hint(index, total, changed_pct):
    if index == 0:
        return HINT_FULL
    if index == total - 1:
        return HINT_FINAL_FULL
    if changed_pct > 35.0:
        return HINT_FULL
    return HINT_PARTIAL


def c_array(name, data):
    lines = [f"const uint8_t {name}[{len(data)}] = {{"]
    for i in range(0, len(data), 16):
        chunk = ", ".join(f"0x{int(b):02X}" for b in data[i:i + 16])
        lines.append(f"    {chunk},")
    lines.append("};")
    return "\n".join(lines)


def emit_assets(frames, hints, width, height, out_dir, output_prefix):
    out_dir.mkdir(parents=True, exist_ok=True)
    header = f"""/* Generated by tools/video2c.py. Do not edit by hand. */
#pragma once

#include <stdint.h>

#define APP_VIDEO_FRAME_W {width}
#define APP_VIDEO_FRAME_H {height}
#define APP_VIDEO_FRAME_LEN {width * height // 8}

typedef enum {{
    APP_REFRESH_PARTIAL = 0,
    APP_REFRESH_FULL = 1,
    APP_REFRESH_FINAL_FULL = 2
}} app_refresh_hint_t;

extern const uint8_t* const APP_VIDEO_FRAMES[];
extern const app_refresh_hint_t APP_VIDEO_REFRESH_HINTS[];
extern const int APP_VIDEO_FRAME_COUNT;
"""
    (out_dir / f"{output_prefix}_assets.h").write_text(header, encoding="utf-8")

    parts = ['/* Generated by tools/video2c.py. Do not edit by hand. */',
             f'#include "{output_prefix}_assets.h"', ""]
    for idx, data in enumerate(frames):
        parts.append(c_array(f"APP_VIDEO_FRAME_{idx:02d}", data))
        parts.append("")

    parts.append("const uint8_t* const APP_VIDEO_FRAMES[] = {")
    for idx in range(len(frames)):
        parts.append(f"    APP_VIDEO_FRAME_{idx:02d},")
    parts.append("};")
    parts.append("")
    parts.append("const app_refresh_hint_t APP_VIDEO_REFRESH_HINTS[] = {")
    for hint in hints:
        parts.append(f"    {hint},")
    parts.append("};")
    parts.append(f"const int APP_VIDEO_FRAME_COUNT = {len(frames)};")
    parts.append("")
    (out_dir / f"{output_prefix}_assets.c").write_text("\n".join(parts), encoding="utf-8")


def emit_fvid(frames, hints, width, height, out_dir, output_prefix):
    """Write the lazy-load SD container consumed by frame_source_sd.cpp."""
    frame_len = width * height // 8
    if frame_len != 5000:
        raise ValueError("FVID currently requires the panel-native 200x200 framebuffer")
    payload = bytearray(struct.pack("<4sBBHHH4s", b"FVID", 1, 0, width, height,
                                    len(frames), b"\0\0\0\0"))
    hint_values = {HINT_PARTIAL: 0, HINT_FULL: 1, HINT_FINAL_FULL: 2}
    for frame, hint in zip(frames, hints):
        raw = bytes(int(value) for value in frame)
        if len(raw) != frame_len:
            raise ValueError(f"frame length {len(raw)} != {frame_len}")
        payload.extend(bytes((hint_values[hint], 0, 0, 0)))
        payload.extend(raw)
    path = out_dir / f"{output_prefix}.fvid"
    path.write_bytes(payload)
    return path


def ink_to_image(ink, scale):
    img = Image.fromarray(np.where(ink, 0, 255).astype(np.uint8), "L")
    return img.resize((ink.shape[1] * scale, ink.shape[0] * scale),
                      Image.Resampling.NEAREST)


def emit_previews(records, out_dir, output_prefix, scale):
    if not records:
        return

    thumbs = [ink_to_image(r["ink"], scale) for r in records]
    strip = Image.new("L", (thumbs[0].width * len(thumbs), thumbs[0].height), 255)
    for idx, img in enumerate(thumbs):
        strip.paste(img, (idx * img.width, 0))
    strip.save(out_dir / "video_preview.png")
    thumbs[-1].save(out_dir / "video_preview_final.png")

    label_h = 28
    sheet = Image.new("RGB", (thumbs[0].width * len(thumbs), thumbs[0].height + label_h), "white")
    draw = ImageDraw.Draw(sheet)
    for idx, img in enumerate(thumbs):
        x = idx * img.width
        sheet.paste(img.convert("RGB"), (x, label_h))
        r = records[idx]
        label = f"{idx:02d} {r['timecode']} {r['changed_pct']:.0f}% {r['hint'].replace('APP_REFRESH_', '')}"
        draw.text((x + 4, 7), label, fill="black")
    sheet.save(out_dir / f"{output_prefix}_contactsheet.png")


def emit_manifest(records, args, fps, out_dir, output_prefix):
    serializable_records = []
    for r in records:
        serializable_records.append({
            "index": r["index"],
            "timecode": r["timecode"],
            "seconds": round(r["seconds"], 6),
            "ink_pct": round(r["ink_pct"], 3),
            "changed_pct": round(r["changed_pct"], 3),
            "refresh_hint": r["hint"],
            "source_frame": str(r["raw"]),
            "processed_frame": str(r["processed"]),
            "crop": r["crop"],
        })

    manifest = {
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "tool": "tools/video2c.py",
        "input": str(args.video),
        "output_prefix": output_prefix,
        "fps": fps,
        "size": args.size,
        "threshold": args.threshold,
        "dither": args.dither,
        "despeckle": args.despeckle,
        "invert": args.invert,
        "frames": serializable_records,
    }
    (out_dir / f"{output_prefix}_manifest.json").write_text(
        json.dumps(manifest, indent=2), encoding="utf-8")


def load_config(path):
    data = json.loads(Path(path).read_text(encoding="utf-8"))
    return data


def parse_args():
    ap = argparse.ArgumentParser()
    ap.add_argument("video", nargs="?")
    ap.add_argument("timecodes", nargs="*", help="mm:ss:ff timecodes")
    ap.add_argument("--config", help="JSON asset-pipeline config")
    ap.add_argument("--size", type=int, default=200)
    ap.add_argument("--threshold", type=int, default=190)
    ap.add_argument("--despeckle", type=int, default=1)
    ap.add_argument("--denoise", action="store_true")
    ap.add_argument("--dither", default="none", choices=["none"])
    ap.add_argument("--invert", action="store_true")
    ap.add_argument("--out", default=str(OUT_DIR))
    ap.add_argument("--frame-dir", default=str(FRAME_DIR))
    ap.add_argument("--scale", type=int, default=3)
    ap.add_argument("--output-prefix", default="family_video")
    ap.add_argument("--format", choices=["c", "fvid"], default="c")
    ap.add_argument("--crop-offset-x", type=int, default=0)
    ap.add_argument("--crop-offset-y", type=int, default=0)
    ap.add_argument("--crop-scale", type=float, default=1.0)
    args = ap.parse_args()

    if args.config:
        cfg = load_config(args.config)
        args.video = cfg.get("input", args.video)
        args.output_prefix = cfg.get("output_prefix", args.output_prefix)
        args.format = cfg.get("format", args.format)
        args.size = int(cfg.get("size", args.size))
        args.threshold = int(cfg.get("threshold", args.threshold))
        args.dither = cfg.get("dither", args.dither)
        args.invert = bool(cfg.get("invert", args.invert))
        args.denoise = bool(cfg.get("denoise", args.denoise))
        args.despeckle = int(cfg.get("despeckle", 1 if args.denoise else args.despeckle))
        args.timecodes = list(cfg.get("frames", args.timecodes))
        crop = cfg.get("crop", {})
        args.crop_offset_x = int(crop.get("offset_x", args.crop_offset_x))
        args.crop_offset_y = int(crop.get("offset_y", args.crop_offset_y))
        args.crop_scale = float(crop.get("scale", args.crop_scale))

    if not args.video:
        raise ValueError("video path is required")
    if not args.timecodes:
        raise ValueError("at least one timecode is required")
    if args.dither != "none":
        raise ValueError("only dither='none' is currently supported")
    return args


def main():
    for stream in (sys.stdout, sys.stderr):
        if hasattr(stream, "reconfigure"):
            stream.reconfigure(encoding="utf-8", errors="replace")

    args = parse_args()
    video = Path(args.video)
    if not video.exists():
        raise FileNotFoundError(video)

    out_dir = Path(args.out)
    frame_dir = Path(args.frame_dir)
    frame_dir.mkdir(parents=True, exist_ok=True)

    crop = {
        "mode": "square",
        "offset_x": args.crop_offset_x,
        "offset_y": args.crop_offset_y,
        "scale": args.crop_scale,
    }

    fps = video_fps(video)
    frames = []
    records = []
    prev_ink = None
    for idx, tc in enumerate(args.timecodes):
        seconds = parse_timecode(tc, fps)
        raw = frame_dir / f"video_stage_{idx:02d}_raw.png"
        extract_frame(video, seconds, raw)
        img, crop_record = fit_square(Image.open(raw).convert("RGB"), args.size, crop)
        processed = frame_dir / f"video_stage_{idx:02d}.png"
        img.save(processed)
        ink = threshold_image(img, args.threshold, args.invert)
        ink = despeckle(ink, args.despeckle)
        changed = change_pct(prev_ink, ink)
        hint = refresh_hint(idx, len(args.timecodes), changed)
        frames.append(pack_native(ink))
        records.append({
            "index": idx,
            "timecode": tc,
            "seconds": seconds,
            "raw": raw,
            "processed": processed,
            "ink": ink,
            "ink_pct": 100.0 * ink.mean(),
            "changed_pct": changed,
            "hint": hint,
            "crop": crop_record,
        })
        prev_ink = ink
        print(f"{idx:02d} {tc} -> {seconds:.3f}s ink {100 * ink.mean():.1f}% "
              f"changed {changed:.1f}% {hint} {processed}")

    hints = [r["hint"] for r in records]
    if args.format == "c":
        emit_assets(frames, hints, args.size, args.size, out_dir, args.output_prefix)
    else:
        print(f"fvid: {emit_fvid(frames, hints, args.size, args.size, out_dir, args.output_prefix)}")
    emit_previews(records, out_dir, args.output_prefix, args.scale)
    emit_manifest(records, args, fps, out_dir, args.output_prefix)
    print(f"\nwrote {len(frames)} frames -> {out_dir}")
    print(f"preview: {out_dir / 'video_preview.png'}")
    print(f"contact sheet: {out_dir / (args.output_prefix + '_contactsheet.png')}")
    print(f"manifest: {out_dir / (args.output_prefix + '_manifest.json')}")


if __name__ == "__main__":
    main()
